services:
  - type: web
    name: contact-automation-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MAIL_SENDER_EMAIL
        fromDatabase:
          name: contact_automation
          property: MAIL_SENDER_EMAIL
      - key: MAIL_SENDER_PASSWORD
        fromDatabase:
          name: contact_automation
          property: MAIL_SENDER_PASSWORD
      - key: MAIL_RECEIVER_EMAIL
        fromDatabase:
          name: contact_automation
          property: MAIL_RECEIVER_EMAIL
